version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  generate_config:
    docker:
      - image: cimg/python:3.10.1 
    steps:
      - checkout # checkout code
      - run:
          name: Python Version Check
          command: python --version
      - run:
          name: List working dir contents
          command: ls -la
      - run:
          name: Install Python deps
          command: pip install -r requirements.txt
      - run:
          name: Generate config
          command: |
            cd pipeline
            python generate_config.py
      - run:
          name: List circleci dir contents
          command: ls -la .circleci
      - run:
          name: Cat generated conf
          command: cat .circleci/generated_config.yml
      - persist_to_workspace:
          root: ./
          paths:
            - .circleci
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: List working dir contents
          command: ls -la
      - run: # run a command
          name: Hello world
          command: echo "Hello world"
      - attach_workspace:
          at: ./  
      - run:
          name: List workspace dir contents
          command: ls -la .circleci
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - generate_config
      - setup:
          requires:
              - generate_config
