version: 2.1

jobs:
  hello_world:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Hello world
          command: echo "Hello, world"

workflows:
  version: 2
  test:
    jobs:
      - hello_world