# https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2

version: 2.1

jobs:
  hello_world:
    working_directory: /tmp/project
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Hello world
          command: echo "Hello, world"

workflows:
  version: 2
  test:
    jobs:
      - hello_world