#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" =~ ^feature\/.* ]]; then
  clean_env_name=${branch//\//-}

  cat > $PWD/terraform/feature/.tfvars <<EOF
wtp_environment = '${clean_env_name}'
wtp_aws_region = 'us-east-1'
EOF
fi


