#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# we only want to run commitizen when we're not rebasing
if [[ ! -d .git/rebase-merge && ! -d .git/rebase-apply ]]; then
  exec < /dev/tty && npx cz --hook || true
fi